# Developer task runner. Run `make` (or `make help`) to
# list the available targets.

.DEFAULT_GOAL := help

# Canonical environment, loaded for every target.
# A missing .env file is not an error.
ifneq (,$(wildcard .env))
include .env
export
endif

# Local overrides, loaded only for dev/test targets so that
# deploy/release targets see the canonical .env values only.
# Sequential include means later assignments win.
DEV_TARGETS := dev test check infra-up infra-down demo
GOALS := $(or $(MAKECMDGOALS),$(.DEFAULT_GOAL))
ifneq (,$(filter $(DEV_TARGETS),$(GOALS)))
ifneq (,$(wildcard .env.local))
include .env.local
export
endif
endif

# Where `make demo` sends its request, and who it greets.
PORT ?= 8080
NAME ?= Temporal

# Default host ports: what `worktree-init` writes unless told otherwise, and
# the fallback for a service that is not running.
GATEWAY_PORT ?= 7233
UI_PORT ?= 8233

# What a running stack publishes is whatever Compose bound, so ask Compose
# rather than guess — the answer already accounts for compose.override.yaml.
# An empty answer means the service is down, and the default above is then the
# right one: `make dev` runs the API on the host, on PORT.
published-port = $$(docker compose port $(1) $(2) 2>/dev/null | cut -d: -f2)

##@ Infra

.PHONY: infra-up
infra-up: ## Start the Temporal dev server and the proxy
	docker compose up -d temporal temporal-proxy

.PHONY: infra-down
infra-down: ## Stop the Temporal dev server and the proxy
	docker compose stop temporal temporal-proxy
	@$(clear-endpoints)

##@ Develop

.PHONY: dev
dev: infra-up ## Start infra, then run the Worker and the HTTP API
	@$(publish-endpoints)
	# Trap reaps the whole process group (kill 0) on exit or signal, so no
	# orphaned processes survive Ctrl-C. Each child calls kill 0 on exit so
	# one crashing process tears the other down instead of leaving a half
	# stack running.
	@gateway=$(call published-port,temporal-proxy,7233); \
		export TEMPORAL_ADDRESS="$${TEMPORAL_ADDRESS:-localhost:$${gateway:-$(GATEWAY_PORT)}}"; \
		trap 'kill 0' EXIT INT TERM; \
		( go run ./cmd/worker; kill 0 ) & \
		( go run ./cmd/api; kill 0 ) & \
		wait

# Compose merges compose.override.yaml automatically, so freezing this
# worktree's ports there — rather than in the environment — makes a bare
# `docker compose up` publish exactly what `make app-up` does. The project
# name is the directory name, unique per worktree, which is what stops two
# worktrees from sharing containers.
.PHONY: worktree-init
worktree-init: ## Fetch dependencies and pin this worktree's ports (overwrites compose.override.yaml)
	go mod download
	@printf '%s\n' \
		'# Host ports and project name for this worktree, generated by' \
		'# `make worktree-init`. Compose merges this file automatically.' \
		'# Not committed.' \
		'#' \
		'# `!override` replaces the port list of a service instead of' \
		'# appending to it, so only the port below is published.' \
		'name: $(notdir $(CURDIR))' \
		'' \
		'services:' \
		'  api:' \
		'    ports: !override' \
		'      - "$(PORT):8080"' \
		'  temporal-proxy:' \
		'    ports: !override' \
		'      - "$(GATEWAY_PORT):7233"' \
		'  temporal:' \
		'    ports: !override' \
		'      - "$(UI_PORT):8233"' \
		> compose.override.yaml

.PHONY: demo
demo: ## Trigger one Workflow through the HTTP API
	@app=$(call published-port,api,8080); \
		curl -fsS -X POST "http://localhost:$${app:-$(PORT)}/hello?name=$(NAME)"

# Markdown on stdout, so the answer to "where is this worktree listening?" can
# be read in a terminal or piped into whatever renders it.
.PHONY: endpoints
endpoints: ## Print this worktree's published endpoints as Markdown
	@app=$(call published-port,api,8080); \
	ui=$(call published-port,temporal,8233); \
	gateway=$(call published-port,temporal-proxy,7233); \
	printf '%s\n' \
		'# temporal-proxy-demo' \
		'' \
		'| Service | Address |' \
		'| --- | --- |' \
		"| Demo App | <http://localhost:$${app:-$(PORT)}> |" \
		"| Temporal Web UI (local) | <http://localhost:$${ui:-$(UI_PORT)}> |" \
		"| Temporal gRPC Proxy | \`localhost:$${gateway:-$(GATEWAY_PORT)}\` |" \
		'' \
		'Trigger a Workflow with `make demo`.'

# The workspace info panel mirrors `make endpoints`, so whichever command
# brought the stack up or down leaves it telling the truth. The CLI is on PATH
# outside a workspace too, hence the CASPER_WORKSPACE_ID test alongside it, and
# `|| true` keeps a panel update from ever failing the target that asked for it.
in-casper-workspace = [ -n "$$CASPER_WORKSPACE_ID" ] && command -v casper >/dev/null 2>&1

define publish-endpoints
$(in-casper-workspace) && $(MAKE) -s endpoints | casper info set - >/dev/null || true
endef

define clear-endpoints
$(in-casper-workspace) && casper info clear >/dev/null || true
endef

##@ Stack

.PHONY: app-up
app-up: ## Bring up the full stack in containers (build + start)
	docker compose up -d --build
	@$(publish-endpoints)

.PHONY: app-down
app-down: ## Tear down the full stack (removes containers and network)
	docker compose down
	@$(clear-endpoints)

##@ Quality

.PHONY: test
test: ## Run the test suite
	go test ./...

.PHONY: check
check: test ## Run tests and static checks
	go vet ./...

##@ Build

.PHONY: build
build: ## Build the production artifact
	go build -o bin/worker ./cmd/worker
	go build -o bin/api ./cmd/api

##@ Helpers

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(firstword $(MAKEFILE_LIST))
